#! /bin/sh
c++ -g -pedantic -Wno-deprecated -O2 -lm -Wall -o eegcode main.cpp connectmat.cpp poplist.cpp population.cpp dendriticrlist.cpp dendriticr.cpp firingr.cpp propagnet.cpp qhistorylist.cpp qhistory.cpp couplinglist.cpp coupling.cpp proplist.cpp waveeqn.cpp stimulus.cpp random.cpp phiout.cpp istrm.cpp propag.cpp parameter.cpp pmap.cpp

