#! /bin/sh
c++ -O2 -lm -o tst main.cpp connectmat.cpp poplist.cpp population.cpp dendriticrlist.cpp dendriticr.cpp firingr.cpp alpha.cpp beta.cpp theta.cpp sigma.cpp qmax.cpp propagnet.cpp qhistorylist.cpp qhistory.cpp couplinglist.cpp coupling.cpp nu.cpp waveeqnlist.cpp waveeqn.cpp effrange.cpp gamma.cpp stimulus.cpp random.cpp phiout.cpp

