#!/usr/bin/perl -w
$in = $ARGV[0];

# if only the configuration file is given, then run once with that config file
if( scalar(@ARGV)<2 ) {
	system "cp $in neurofield.output";
	exec "make run";
}

# if N(>=2) additional arguments are given, then modify $field on $line N-1 times with given values

$line = $ARGV[1];
$field = $ARGV[2];

`make`;

for(my $i=3; $i<scalar(@ARGV); $i++)
{
	print "Running with $line: $field = $ARGV[$i]:\n";
	$dir = "Output/$field=$ARGV[$i]";
	`mkdir -p $dir`;
	chdir $dir;
	open IN,  "<../../$in"  or die $!;
	open OUT, ">neurofield.conf" or die $!;
	while(<IN>) {
		$write = $_;
		$write =~ s/$field:\s+(-[\d\.e]+)/$field: $ARGV[$i]/ if(/^\s*$line/);
		print OUT "$write";
	}
	close IN;
	close OUT;
	`../../Release/NeuroField`;
	chdir "../.."
}
